### ISSUE TITLE
Read this 

### ISSUE THREAD

**Issue by nykeztv** [nykeztv/GTABugs#1]
Found a bug on the GTA gamemode? Reporting it has never been easier. By using this system I can recreate the bugs, fix the bugs, and release the fix much quicker.

It's very simple.

Go to this link: https://github.com/nykeztv/GTABugs/issues

Then click the nice green button labeled 'New Issue'

**Comment by DFG-Kevin** [comment]
It think there is a bug in the park, you can see a person standing in the air :)

**Comment by DFG-Kevin** [comment]
I think there is a bug, every time you start a car and hold space down it gives a Script error :) But only with some cars. I think it's the start sound :) Need to be changed to a new sound that works :)
